---
meta:
  environment: (( param "Please define your deployment environment" ))
  stemcell: (( param "No stemcell detected..." ))

name: (( grab meta.environment ))

director_uuid: (( param "No director UUID supplied..." ))

releases: (( param "No releases defined" ))
networks: (( param "No networks defined" ))
jobs:     (( param "No jobs defined" ))

compilation:
  workers: 6
  network: (( grab networks.default.name ))
  reuse_compilation_vms: true
  cloud_properties: (( param "Cloud properties must be specified by the infrastructure templates" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: docker_registry1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "Cloud properties must be specified by the infrastructure templates" ))
