meta:
  security_groups: (( param "You must define security groups for your Openstack deployment" ))
  network_name:    (( param "You must define a network name for your Openstack deployment" ))

  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

jobs:
  - name: registry
    instances: 1
    networks:
      - name: (( grab meta.network_name ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: (( grab meta.network_name ))
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
