---
meta:
  environment: docker-registry-warden
  network_name: (( param "You must define a network name for your Warden/BOSH-lite deployment" ))

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: registry
    instances: 1
    networks:
      - name: (( grab meta.network_name ))
        static_ips: (( static_ips(0) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: (( grab meta.network_name ))
  subnets:
  - range: 10.244.4.0/24
    cloud_properties:
      name: random
    reserved:
    - 10.244.4.1 - 10.244.4.10
    static:
    - 10.244.4.11
