meta:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: registry
    instances: 1
    networks:
      - name: (( grab networks.default.name ))
        default:
          - dns
          - gateway
      - name: elastic
        static_ips: (( grab meta.floating_ip ))
  - name: smoke-tests
    instances: 1
    networks:
      - name: (( grab networks.default.name ))

compilation:
  cloud_properties:
    instance_type: t2.small

disk_pools:
- name: registry
  disk_size: 102400

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: t2.small
