meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: docker_registry_leader_z1
    template: docker-registry
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
  - name: docker_registry_z1
    template: docker-registry
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties:
      docker_registry:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
