---
meta:
  name:    docker-registry
  release: Docker Registry
  target:  pipes-main
  url:     https://pipes.starkandwayne.com

  initial_version: 3.1.0

  bosh:
    target: https://10.200.131.9:25555
    deployment: docker-registry-warden
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    ca-cert:  ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   docker-registry-boshrelease
    branch: master
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  slack:
    webhook: ((slack.webhook))
    channel: '#botspam'
